# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: latest
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python setup.py install
        pip install codecov pytest-cov
    - name: Test with pytest
      run: |
        pytest -v --cov=audearch --cov-report=xml
    - name: Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        file: ./coverage.xml
