# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.7, 3.6]

    steps:
    - uses: actions/checkout@v2
    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: latest
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools --upgrade
        python setup.py install
        pip install codecov pytest-cov
    - name: Test with pytest
      run: |
        pytest -v --cov=audearch --cov-report=xml
    - name: Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        file: ./coverage.xml
    - name: Discord Notification 
      uses: sarisia/actions-status-discord@v1
      if: always()
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORDWEBHOOK }}
      with:
        status: ${{ job.status }}
